'use strict';
const Anthropic = require('@anthropic-ai/sdk');

let _client;
function getClient() {
  if (!_client) {
    if (!process.env.ANTHROPIC_API_KEY) {
      throw new Error('ANTHROPIC_API_KEY is not set in environment variables.');
    }
    _client = new Anthropic({ apiKey: process.env.ANTHROPIC_API_KEY });
  }
  return _client;
}

function buildSystemPrompt(prediction) {
  const seqClean = (prediction.fastaSequence || '')
    .replace(/^>.*$/gm, '')
    .replace(/\s/g, '');

  const topCandidates = (prediction.candidates || []).slice(0, 8);
  const candidateLines = topCandidates.length
    ? topCandidates.map(c =>
        `  • ${c.mutation}: ddG=${c.ddG ?? '?'} kcal/mol` +
        (c.predictedStabilityChange != null ? `, ΔTm≈${c.predictedStabilityChange}°C` : '') +
        (c.activityRisk != null ? `, activityRisk=${c.activityRisk}` : '') +
        (c.structuralReason ? ` — ${c.structuralReason}` : '')
      ).join('\n')
    : '  (no candidates available yet)';

  const highPotentialHotspots = (prediction.hotspotMap || [])
    .filter(h => h.stabilizationPotential > 0.55)
    .sort((a, b) => b.stabilizationPotential - a.stabilizationPotential)
    .slice(0, 6)
    .map(h =>
      `  • Pos ${h.position} (${h.residue}): stabilizationPotential=${h.stabilizationPotential}, mutationalTolerance=${h.mutationalTolerance}`
    ).join('\n');

  return `You are an expert protein engineering AI assistant for the hsFAST Enzyme Stability ML Prediction Platform. \
You help researchers understand, interpret, and act on protein stability predictions generated by a Gradient Boosting model \
trained on the S1724 ThermoMutDB benchmark with ESM-2 masked marginal features.

## Prediction Context
- **Sequence length**: ${seqClean.length} residues
- **Conditions**: pH ${prediction.conditions?.ph ?? 7.0}, ${prediction.conditions?.temperature ?? 25}°C
- **Model version**: ${prediction.modelVersion || 'v4.0-structural'}
- **Status**: ${prediction.status}
${prediction.similarityWarning ? '- ⚠️ **Similarity warning**: query sequence is outside training distribution.' : ''}
${prediction.conditionOutOfRange ? `- ⚠️ **Condition note**: ${prediction.conditionNote}` : ''}

## Top Stabilizing Mutation Candidates (ranked by predicted ΔΔG)
Convention: negative ddG = stabilising (traditional biochemistry).
${candidateLines}

## High-Potential Hotspot Positions
${highPotentialHotspots || '  None above threshold'}

## How to Respond
- Reference specific mutations by name (e.g., A42V) when discussing predictions.
- Explain physicochemical reasoning (hydrophobicity, charge, volume, burial, BLOSUM62) when relevant.
- Be concise but scientifically accurate. Acknowledge model uncertainty (protein-CV R²≈0.19).
- If asked about mutations not listed above, note they were ranked lower by the model.
- Suggest experimental validation priorities when asked for next steps.`;
}

/**
 * Call Claude and return the assistant's reply text.
 * chatHistory: array of { role: 'user'|'assistant', content: string }
 * The last element must be the new user message.
 */
async function generateChatResponse(prediction, chatHistory) {
  const client = getClient();

  const messages = chatHistory.map(msg => ({
    role: msg.role,
    content: msg.content,
  }));

  const stream = client.messages.stream({
    model: 'claude-opus-4-8',
    max_tokens: 1024,
    thinking: { type: 'adaptive' },
    system: buildSystemPrompt(prediction),
    messages,
  });

  const response = await stream.finalMessage();
  const textBlock = response.content.find(b => b.type === 'text');
  return textBlock?.text ?? 'Unable to generate a response.';
}

module.exports = { generateChatResponse };
